config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'herbs#index', as: 'home'

  # gets /about route from pages
  get 'about' => 'pages#about'

  # declares common CRUD routes
  resources :herbs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/herb.rb
class Herb < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/herbs_controller.rb
class HerbsController < ApplicationController
  def index
    @herbs = Herb.all
  end

  def show
    # find the herb's id from the Herb model
    @herb = Herb.find(params[:id])
  end

  def new
    @herb = Herb.new
  end

  def create
    # shows data being sent
    # render plain: params[:herb].inspect

    # creates new herb from params in Herb model
    @herb = Herb.new(herb_params)

    if(@herb.save)
      redirect_to @herb
    else
      render 'new'
    end
  end

  def edit
    @herb = Herb.find(params[:id])
  end

  def update
    @herb = Herb.find(params[:id])

    if(@herb.update(herb_params))
      redirect_to @herb
    else
      render 'edit'
    end
  end

  def destroy
    @herb = Herb.find(params[:id])
    @herb.destroy

    redirect_to herbs_path
  end

  # defines params needed for create method
  private def herb_params
    params.require(:herb).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/herbs_helper.rb
module HerbsHelper
end

app/views/herbs/edit.html.erb
<div class="edit">
  <h1>Edit Herb</h1>
  <%= form_for :herb, :html => {:class => 'edit__form'}, url: herb_path(@herb), method: :patch do |f| %>
    <% if @herb.errors.any? %>
      <%# loop %>
      <% @herb.errors.full_messages.each do |msg| %>
        <div class="form__error">
          <%= msg %>
        </div>
      <% end %>
    <% end %>
    <div class="edit__field-wrapper">
      <%= f.label :name %>
      <br>
      <%= f.text_field(:name, {:class => 'edit__field'}) %>
    </div>
    
    <div class="edit__field-wrapper">
      <%= f.label :description %>
      <br>
      <%= f.text_area(:description, {:class => 'edit__field'}) %>
    </div>

    <div class="edit__field-wrapper">
      <%= f.submit(:class => 'edit__submit') %>
    </div>
  <% end %>
</div>

app/views/herbs/index.html.erb
<div class="home">
  <h1>Fav Herbs</h1>
  <div class="home__card-wrapper">
    <% @herbs.each do |herb| %>
      <% if herb.name %>
        <div class="home__card">
          <%= link_to herb_path(herb), :class => 'home__card-inner' do %>
            <h3 class="home__name"><%= herb.name %></h3>
            <p class="home__description"><%= herb.description %></p>
            <p class="home__more">Read more &#8594;</p>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/herbs/new.html.erb
<div class="add">
  <h1>Add Herb</h1>
  <%= form_for :herb, :html => {:class => 'add__form'}, url: herbs_path do |f| %>
    <% if @herb.errors.any? %>
      <%# loop %>
      <% @herb.errors.full_messages.each do |msg| %>
        <div class="form__error">
          <%= msg %>
        </div>
      <% end %>
    <% end %>
    <div class="add__field-wrapper">
      <%= f.label :name %>
      <br>
      <%= f.text_field(:name, {:class => 'add__field'}) %>
    </div>
    
    <div class="add__field-wrapper">
      <%= f.label :description %>
      <br>
      <%= f.text_area(:description, {:class => 'add__field'}) %>
    </div>

    <div class="add__field-wrapper">
      <%= f.submit(:class => 'add__submit') %>
    </div>
  <% end %>
</div>

app/views/herbs/show.html.erb
<div class="herb">
  <div class="herb__top">
    <h2 class="herb__name"><%= @herb.name %></h2>
    <div class="herb__actions">
      <%= link_to 'Edit', edit_herb_path(@herb), :class => 'herb__action-btn herb__action-btn--edit' %>
      <%= link_to 'Delete', herb_path(@herb), method: :delete, data: {confirm: 'Delete this herb?'}, :class => 'herb__action-btn herb__action-btn--delete' %>
    </div>
  </div>
  <div class="herb__description-wrapper">
    <p class="herb__description"><%= @herb.description %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Herbs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="nav">
      <div class="nav__inner">
        <div class="nav__left">
          <span class="nav__logo">
            <%= link_to "Home", home_path %>
          </span>
        </div>
        <div class="nav__right">
          <ul class="nav__menu">
            <li class="nav__menu-item">
              <%= link_to "Home", home_path %>
            </li>
            <li class="nav__menu-item">
              <%= link_to "Add Herb", new_herb_path %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>